# Generated by Django 2.0.4 on 2018-05-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotnisko_startowe', models.CharField(max_length=100)),
                ('czas_startu', models.DateTimeField()),
                ('lotnisko_docelowe', models.CharField(max_length=100)),
                ('czas_ladowania', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasazer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pasazer_Lotu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplanes_app.Lot')),
                ('pasazer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplanes_app.Pasazer')),
            ],
        ),
        migrations.CreateModel(
            name='Samolot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znaki_rejestracyjne', models.CharField(max_length=20)),
                ('liczba_miejsc', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='samolot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplanes_app.Samolot'),
        ),
    ]
