# Generated by Django 2.0.4 on 2018-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasazer_lotu',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='pasazer_lotu',
            name='pasazer',
        ),
        migrations.AddField(
            model_name='lot',
            name='pasazerowie',
            field=models.ManyToManyField(to='airplanes_app.Pasazer'),
        ),
        migrations.DeleteModel(
            name='Pasazer_Lotu',
        ),
    ]
