# Generated by Django 2.0.5 on 2018-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0002_auto_20180510_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='zajete_miejsca',
            field=models.IntegerField(default=0),
        ),
    ]
