# Generated by Django 2.0.5 on 2018-05-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0003_lot_zajete_miejsca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='zajete_miejsca',
            new_name='liczba_zajetych_miejsca',
        ),
    ]
