# Generated by Django 2.0.5 on 2018-05-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0004_auto_20180510_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='liczba_zajetych_miejsca',
            new_name='liczba_zajetych_miejsc',
        ),
    ]
