# Generated by Django 2.0.5 on 2018-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0005_auto_20180510_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_kapitana', models.CharField(max_length=100)),
                ('nazwisko_kapitana', models.CharField(max_length=100)),
            ],
        ),
    ]
