# Generated by Django 2.0.5 on 2018-05-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0007_lot_zaloga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='zaloga',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='airplanes_app.Zaloga'),
        ),
    ]
