# Generated by Django 2.0.5 on 2018-05-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0009_auto_20180516_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='zaloga',
        ),
    ]
