# Generated by Django 2.0.5 on 2018-05-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0013_auto_20180516_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='zaloga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airplanes_app.Zaloga'),
        ),
    ]
