# Generated by Django 2.0.5 on 2018-06-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0014_auto_20180516_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='zaloga',
        ),
    ]
