# Generated by Django 2.0.5 on 2018-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0016_delete_zaloga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko_kapitana', models.CharField(max_length=200)),
            ],
        ),
    ]
