# Generated by Django 2.0.5 on 2018-06-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes_app', '0017_zaloga'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='zaloga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airplanes_app.Zaloga'),
        ),
    ]
